name: English Please
on:
  issues:
    types: [opened, edited, labeled]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3/v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: main
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run English Please
        uses: ./actions/english-please
        with:
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          cognitiveServicesAPIKey: ${{secrets.AZURE_TEXT_TRANSLATOR_KEY}}
          nonEnglishLabel: "*english-please"
          needsMoreInfoLabel: "needs more info"
          translatorRequestedLabelPrefix: "translation-required-"
          translatorRequestedLabelColor: "c29cff"
